Repository AY2122S2-CS2103T-W11-3/tp, pull requests merged in 2022-04, with the labels that each got.

#235 Rename `findstudent` and `findlesson` to...
  docs/UserGuide.md
Labels: bug, documentation

#172 Fix bugs
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/lesson/ConsistentLessonList.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/main/java/seedu/address/model/lesson/exceptions/ConflictsWithLessonsException.java
  src/main/java/seedu/address/model/student/NameOrTagsContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedDateTimeSlot.java
  src/main/java/seedu/address/storage/JsonSerializableLessonBook.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/seedu/address/model/lesson/ConsistentLessonListTest.java
Labels: bug, backend

#237 Fix startup bug related to storage
  src/main/java/seedu/address/storage/JsonAdaptedDateTimeSlot.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/test/data/JsonLessonBookStorageTest/invalidAndValidLessonsLessonBook.json
  src/test/data/JsonLessonBookStorageTest/invalidLessonBook.json
  src/test/data/JsonLessonBookStorageTest/notJsonFormatLessonBook.json
  src/test/data/JsonSerializableLessonBookTest/conflictingLessonBook.json
  src/test/data/JsonSerializableLessonBookTest/invalidLessonBook.json
  src/test/data/JsonSerializableLessonBookTest/typicalLessonBook.json
  src/test/java/seedu/address/storage/JsonAdaptedLessonTest.java
  src/test/java/seedu/address/storage/JsonLessonBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableLessonBookTest.java
  src/test/java/seedu/address/testutil/LessonBookBuilder.java
  src/test/java/seedu/address/testutil/RecurringLessonBuilder.java
  src/test/java/seedu/address/testutil/TypicalLessons.java
Labels: bug

#241 Fix bug where `RecurringLesson` conflicts with `TemporaryLesson` that…
  src/main/java/seedu/address/model/lesson/RecurringLesson.java
Labels: bug

#238 Fix wrong error message when index out of bounds is input for `assign…
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
Labels: bug

#245 Bug fixes for UI messages and UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
Labels: bug, documentation

#244 Bugfixes limit field lengths
  docs/UserGuide.md
  src/main/java/seedu/address/model/lesson/LessonAddress.java
  src/main/java/seedu/address/model/lesson/LessonName.java
  src/main/java/seedu/address/model/lesson/Subject.java
  src/main/java/seedu/address/model/student/Address.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/resources/view/LessonInfoPanel.fxml
  src/main/resources/view/RecurringLessonInfoPanel.fxml
  src/main/resources/view/RecurringLessonListCard.fxml
  src/main/resources/view/StudentInfoPanel.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/TemporaryLessonListCard.fxml
  src/test/java/seedu/address/model/lesson/LessonNameTest.java
  src/test/java/seedu/address/model/student/AddressTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/PhoneTest.java
  src/test/java/seedu/address/model/student/StudentNameTest.java
Labels: documentation

#247 Add testcases for `AssignCommand` and `UnassignCommand`
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
Labels: backend

#246 Code quality 1
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/main/java/seedu/address/storage/JsonAdaptedDateTimeSlot.java
  src/test/java/seedu/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/seedu/address/model/lesson/DateTimeSlotTest.java
Labels: bug

#248 Add details to Kidsnd274's PPP and minor changes to the DG
  docs/DeveloperGuide.md
  docs/team/kidsnd274.md
Labels: documentation

#250 Fix bug where info panel does not refresh after command
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/misc/InfoPanelTypes.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#253 Fix use-cases section in Developer Guide
  docs/DeveloperGuide.md
Labels: bug, documentation

#252 Update nnmoq's PPP
  docs/team/nnmoq.md
Labels: documentation

#251 Code quality improvements for command and parser classes
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/FindLessonCommand.java
  src/main/java/seedu/address/logic/commands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/ListLessonsCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonInfoCommand.java
  src/main/java/seedu/address/logic/commands/ViewStudentInfoCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/misc/ViewTab.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/FindLessonCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: enhancement

#256 Update PPP ryanlow
  docs/team/ryan-l98.md
Labels: documentation

#254 Fix GitHub page's user guide formatting
  docs/UserGuide.md
Labels: bug, documentation

#257 Add short description of responsibilities of team-members to AboutUS
  docs/AboutUs.md
Labels: documentation

#255 Add test cases for UserInputHistory package
  src/main/java/seedu/address/logic/inputhistory/InputHistoryResult.java
  src/main/java/seedu/address/logic/inputhistory/UserInputHistory.java
  src/main/java/seedu/address/logic/inputhistory/UserInputIndex.java
  src/main/java/seedu/address/logic/inputhistory/UserInputString.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/inputhistory/InputHistoryResultTest.java
  src/test/java/seedu/address/logic/inputhistory/UserInputHistoryTest.java
  src/test/java/seedu/address/logic/inputhistory/UserInputIndexTest.java
  src/test/java/seedu/address/logic/inputhistory/UserInputStringTest.java
Labels: backend

#258 Improvements to test cases
  src/test/java/seedu/address/logic/inputhistory/UserInputHistoryTest.java
Labels: backend

#259 Fix formatting of PPP
  docs/team/nnmoq.md
Labels: bug, documentation

#260 Update Developer Guide with Storage component details and class diagram
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/team/ryan-l98.md
Labels: documentation

#261 Update DG and nnmoq's PPP
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/team/nnmoq.md
Labels: documentation

#262 Improve and update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/team/kidsnd274.md
Labels: documentation

#263 DG and UG bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#264 Update PPP
  docs/team/jamesyeap.md
Labels: documentation

#265 Add instructions to test...
  docs/DeveloperGuide.md
  docs/team/jamesyeap.md
Labels: documentation

#268 Add manual testing instructions for `assign` and` `unassign`
  docs/DeveloperGuide.md
  docs/team/ryan-l98.md
Labels: documentation

#269 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteLessonSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteStudentSequenceDiagram.puml
  docs/images/AddStudentSequenceDiagram-0.png
  docs/images/AddStudentSequenceDiagram-1.png
  docs/images/AddStudentSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteLessonSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteStudentSequenceDiagram.png
Labels: documentation

#266 Add manual testing instructions
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kidsnd274.md
Labels: documentation

#267 Add test cases for TeachWhatParser
  build.gradle
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/test/java/seedu/address/logic/parser/TeachWhatParserTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: backend

#271 Small minor adjustments to DG for standardization
  docs/DeveloperGuide.md
Labels: documentation

#273 Additional adjustments to DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: documentation

#272 Add help feature to DG
  docs/DeveloperGuide.md
  docs/diagrams/TableView.puml
  docs/images/TableView.png
  docs/team/nnmoq.md
Labels: documentation

#274 Update UG to use optional prefixes.
  docs/UserGuide.md
Labels: documentation

#275 Update header with new title when printing docs
  docs/_sass/minima/_base.scss
Labels: documentation

#276 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentSequenceDiagram.puml
  docs/images/AddStudentSequenceDiagram-0.png
  docs/images/AddStudentSequenceDiagram-1.png
Labels: documentation

#278 Update nnmoq's ppp
  docs/team/nnmoq.md
Labels: documentation

#280 Added page breaks to Kidsnd274's PPP
  docs/team/kidsnd274.md
Labels: documentation

#282 Reduce PPP header size
  docs/team/nnmoq.md
Labels: documentation

#281 Fix PPP format
  docs/team/ryan-l98.md
Labels: documentation

#283 Update PPP for jamesyeap
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jamesyeap.md
Labels: documentation

#284 Adjustments to spacing and remove header when printing
  docs/_sass/minima/_base.scss
  docs/_sass/minima/initialize.scss
  docs/team/kidsnd274.md
Labels: documentation

#285 Update PPP
  docs/team/nnmoq.md
Labels: documentation

#287 Fix PPP 2
  docs/team/jamesyeap.md
Labels: documentation

#291 Update version
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#293 Update DG hyperlinks
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: bug, documentation

#295 Add userstories
  docs/DeveloperGuide.md
Labels: documentation

#299 Amend jar file name to `TeachWhat.jar`
  build.gradle
Labels: bug
