Repository AY2122S2-CS2103T-W11-3/tp, pull requests merged in 2022-03, with the labels that each got.

#57 Add UI component and models for Lessons
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/LessonBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyLessonBook.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/Name.java
  src/main/java/seedu/address/model/lesson/Subject.java
  src/main/java/seedu/address/model/lesson/TemporaryLesson.java
  src/main/java/seedu/address/model/lesson/TimeSlot.java
  src/main/java/seedu/address/model/lesson/UniqueLessonList.java
  src/main/java/seedu/address/model/lesson/exceptions/ConflictsWithLessonException.java
  src/main/java/seedu/address/model/lesson/exceptions/LessonNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/LessonListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/teachwhaticon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LessonListCard.fxml
  src/main/resources/view/LessonListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: help wanted, backend

#62 Add UI info panels for Person and Lesson
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/infopanel/InfoPanel.java
  src/main/java/seedu/address/ui/infopanel/LessonInfoPanel.java
  src/main/java/seedu/address/ui/infopanel/PersonInfoPanel.java
  src/main/java/seedu/address/ui/listpanel/LessonListPanel.java
  src/main/java/seedu/address/ui/listpanel/ListPanel.java
  src/main/java/seedu/address/ui/listpanel/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LessonInfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonInfoPanel.fxml
Labels: help wanted

#61 Add temporary class command
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/model/LessonBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/LessonAddress.java
  src/main/java/seedu/address/model/lesson/LessonName.java
  src/main/java/seedu/address/model/lesson/Subject.java
  src/main/java/seedu/address/model/lesson/TemporaryLesson.java
  src/main/java/seedu/address/model/lesson/TimeSlot.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/lesson/DateTimeSlotTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/model/lesson/NameTest.java
  src/test/java/seedu/address/model/lesson/SubjectTest.java
  src/test/java/seedu/address/model/lesson/TemporaryLessonTest.java
  src/test/java/seedu/address/model/lesson/UniqueLessonListTest.java
Labels: help wanted

#63 Add view commands for Student and Class
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewLessonInfoCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonInfoCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/NoInfoPanelTypeException.java
  src/main/java/seedu/address/logic/commands/misc/InfoPanelTypes.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/logic/parser/ViewLessonInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewPersonInfoCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewLessonInfoCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewPersonInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewLessonInfoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewPersonInfoCommandParserTest.java
Labels: help wanted

#67 Update user guide
  docs/UserGuide.md
Labels: documentation

#70 Add deletion functionality for lessons.
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/model/LessonBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#69 Add additional checks for add lesson command
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/seedu/address/model/lesson/DateTimeSlotTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
Labels: backend

#76 Remove duplicate prefix functionality
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: core change

#75 Add lesson storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/Subject.java
  src/main/java/seedu/address/model/lesson/TemporaryLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedDateTimeSlot.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonLessonBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableLessonBook.java
  src/main/java/seedu/address/storage/LessonBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/infopanel/LessonInfoPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement

#68 Implement `liststudents` and `listlessons` commands
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListLessonsCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/ViewTab.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#74 Add assign students lessons
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CheckPrefixes.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/LessonBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/EnrolledStudents.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/TemporaryLesson.java
  src/main/java/seedu/address/model/lesson/UniqueLessonList.java
  src/main/java/seedu/address/model/student/EnrolledLessons.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/infopanel/LessonInfoPanel.java
  src/main/java/seedu/address/ui/infopanel/StudentInfoPanel.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerUtil.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: help wanted, story

#80 Implement Resizable UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#83 Update User guide
  docs/UserGuide.md
Labels: documentation

#84 Fix resizable list from info panel
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/infopanel/LessonInfoPanel.java
  src/main/java/seedu/address/ui/infopanel/StudentInfoPanel.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#82 Implement recurring lessons
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/LessonBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/RecurringLesson.java
  src/main/java/seedu/address/model/lesson/TemporaryLesson.java
  src/main/java/seedu/address/model/lesson/UniqueLessonList.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonSerializableLessonBook.java
  src/main/resources/view/LessonInfoPanel.fxml
  src/main/resources/view/StudentInfoPanel.fxml
Labels: enhancement

#90 Fix recurring lesson and `assign` command bug
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/model/lesson/RecurringLesson.java
Labels: bug

#91 Refactor lesson models
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/RecurringLesson.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/test/java/seedu/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/model/lesson/UniqueLessonListTest.java
  src/test/java/seedu/address/testutil/RecurringLessonBuilder.java
  src/test/java/seedu/address/testutil/TemporaryLessonBuilder.java
  src/test/java/seedu/address/testutil/TypicalLessons.java
Labels: backend

#127 Update developer guide
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/AssignSequenceDiagram.puml
  docs/diagrams/AssignState0.puml
  docs/diagrams/AssignState1.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/style.puml
  src/main/resources/images/AssignSequenceDiagram.png
  src/main/resources/images/AssignState0-Initial_state.png
  src/main/resources/images/AssignState1-Final_state.png
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: documentation

#128 Amend assign command
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/LessonBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/ConsistentLessonList.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: core change

#129 Add switching of tabs when new `Student` or `Lesson` is added
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: enhancement

#131 Update UI design component part of the developer guide
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/uidiagrams/InfoPanelClassDiagram.puml
  docs/diagrams/uidiagrams/ListPanelClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/UiPhotos/BottomHalf.png
  docs/images/UiPhotos/InfoPanelClassDiagram.png
  docs/images/UiPhotos/ListPanelClassDiagram.png
  docs/images/UiPhotos/UiClassDiagram.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/card/Card.java
  src/main/java/seedu/address/ui/card/LessonCard.java
  src/main/java/seedu/address/ui/card/StudentCard.java
  src/main/java/seedu/address/ui/infopanel/LessonInfoPanel.java
  src/main/java/seedu/address/ui/infopanel/StudentInfoPanel.java
  src/main/java/seedu/address/ui/listpanel/LessonListPanel.java
  src/main/java/seedu/address/ui/listpanel/StudentListPanel.java
Labels: documentation

#132 Fix typo in Developer Guide...
  docs/DeveloperGuide.md
Labels: documentation

#130 Fix bug where adding back-to-back lessons raises a conflicting lessons exception
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
Labels: bug

#133 Remove restriction for adding past lessons
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddLessonCommandParserTest.java
Labels: enhancement

#135 Implement `unassign` command
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: enhancement

#139 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentSequenceDiagram.puml
  src/main/resources/images/AddStudentSequenceDiagram.png
Labels: documentation

#140 Update Developer Guide
  docs/DeveloperGuide.md
  docs/images/AddStudentSequenceDiagram.png
  docs/images/AssignSequenceDiagram.png
  docs/images/AssignState0-Initial_state.png
  docs/images/AssignState1-Final_state.png
Labels: documentation

#136 Implement `findlesson` command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindLessonCommand.java
  src/main/java/seedu/address/logic/parser/FindLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/model/lesson/LessonNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/lesson/LessonNameContainsKeywordsPredicateTest.java
Labels: enhancement, story

#143 Add sequence diagram to implementation...
  docs/DeveloperGuide.md
  docs/diagrams/AddLessonSequenceDiagram.puml
  docs/images/AddLessonSequenceDiagram.png
Labels: documentation

#146 Add edit student command
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/parser/EditStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudentBookParserTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: enhancement

#151 Implement edit `Lesson` command
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/test/java/seedu/address/logic/parser/AddLessonCommandParserTest.java
Labels: enhancement

#152 Implement sorted Lessons by date
  src/main/java/seedu/address/ui/listpanel/LessonListPanel.java
Labels: enhancement

#155 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#157 Fix bug where `listlessons` command does not list all lessons
  src/main/java/seedu/address/logic/commands/ListLessonsCommand.java
Labels: bug

#145 Add command shortcuts
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/FindLessonCommand.java
  src/main/java/seedu/address/logic/commands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/ListLessonsCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonInfoCommand.java
  src/main/java/seedu/address/logic/commands/ViewStudentInfoCommand.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/test/java/seedu/address/logic/parser/EditStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudentBookParserTest.java
Labels: enhancement, backend

#144 Show conflicting lessons in UI
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/model/lesson/ConflictingLessonsPredicate.java
  src/test/java/seedu/address/model/lesson/ConflictingLessonsPredicateTest.java
Labels: enhancement

#147 Add styling for recurring lessons in the UI
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/RecurringLesson.java
  src/main/java/seedu/address/model/lesson/TemporaryLesson.java
  src/main/java/seedu/address/ui/card/RecurringLessonCard.java
  src/main/java/seedu/address/ui/card/StudentCard.java
  src/main/java/seedu/address/ui/card/TemporaryLessonCard.java
  src/main/java/seedu/address/ui/infopanel/StudentInfoPanel.java
  src/main/java/seedu/address/ui/listpanel/LessonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RecurringLessonListCard.fxml
  src/main/resources/view/TemporaryLessonListCard.fxml
Labels: enhancement

#150 Add user input history function
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/inputhistory/InputHistoryResult.java
  src/main/java/seedu/address/logic/inputhistory/UserInputHistory.java
  src/main/java/seedu/address/logic/inputhistory/UserInputIndex.java
  src/main/java/seedu/address/logic/inputhistory/UserInputString.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
Labels: enhancement

#149 Separate sequence diagram used in the Implementation section for the …
  docs/DeveloperGuide.md
  docs/diagrams/AddLessonSequenceDiagram_1.puml
  docs/diagrams/AddLessonSequenceDiagram_2.puml
  docs/images/AddLessonSequenceDiagram.png
  docs/images/AddLessonSequenceDiagram_1.png
  docs/images/AddLessonSequenceDiagram_2.png
Labels: documentation

#159 Add unit tests for DateTimeSlot
  src/main/java/seedu/address/model/lesson/DateTimeSlot.java
  src/test/java/seedu/address/model/lesson/DateTimeSlotTest.java
Labels: backend

#158 Update help page
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindLessonCommand.java
  src/main/java/seedu/address/logic/commands/FindStudentCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListLessonsCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonInfoCommand.java
  src/main/java/seedu/address/logic/commands/ViewStudentInfoCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement, backend

#161 Update `addlesson` section in User Guide
  docs/UserGuide.md
Labels: documentation

#160 Update Implementation Section of Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddLessonObjectDiagram_1.puml
  docs/diagrams/AddLessonObjectDiagram_2.puml
  docs/diagrams/AddLessonObjectDiagram_3.puml
  docs/diagrams/AddLessonObjectDiagram_4.puml
  docs/diagrams/AddLessonSequenceDiagram_1.puml
  docs/diagrams/AddLessonSequenceDiagram_2.puml
  docs/diagrams/AddLessonSequenceDiagram_3.puml
  docs/diagrams/AddLessonSequenceDiagram_4.puml
  docs/diagrams/AddLessonSequenceDiagram_5.puml
  docs/images/AddLessonObjectDiagram_4.png
  docs/images/AddLessonSequenceDiagram_1.png
  docs/images/AddLessonSequenceDiagram_2.png
  docs/images/AddLessonSequenceDiagram_3.png
  docs/images/AddLessonSequenceDiagram_4.png
  docs/images/AddLessonSequenceDiagram_5.png
  src/main/java/seedu/address/model/ModelManager.java
Labels: documentation

#162 Update UG with viewing previous commands feature
  docs/UserGuide.md
Labels: documentation

#163 Fix styling in User Guide
  docs/UserGuide.md
  docs/diagrams/AddLessonSequenceDiagram_5.puml
  docs/images/AddLessonSequenceDiagram_5.png
Labels: documentation

#164 Update user guide
  docs/UserGuide.md
Labels: documentation

#166 Add clear -f command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/misc/InfoPanelTypes.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/listpanel/LessonListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/StudentBookParserTest.java
Labels: enhancement

#167 Fix bugs in `addlesson` and `addstudent` commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/model/lesson/exceptions/ConflictsWithLessonsException.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#168 More updates to the user guide
  docs/UserGuide.md
Labels: documentation

#169 Update sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddLessonSequenceDiagram_1.puml
  docs/images/AddLessonSequenceDiagram_1.png
Labels: documentation

#171 Fix bugs with `edit` commands and `findlesson` command
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/FindLessonCommand.java
  src/main/java/seedu/address/logic/parser/FindLessonCommandParser.java
  src/main/java/seedu/address/model/lesson/LessonNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/lesson/LessonNameOrSubjectContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/lesson/LessonNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/lesson/LessonNameOrSubjectContainsKeywordsPredicateTest.java
Labels: bug

#170 Fix bug where lessons are not removed when cleared
  build.gradle
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/ConsistentLessonList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: bug

#173 Update release version and bug fixes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/TeachWhatParser.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LessonInfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentInfoPanel.fxml
Labels: bug, documentation

#176 Update the User Guide...
  docs/UserGuide.md
Labels: documentation

#174 Fix sequence diagrams for implementation of AddLessonCommand...
  docs/diagrams/AddLessonSequenceDiagram_1.puml
  docs/diagrams/AddLessonSequenceDiagram_4.puml
  docs/diagrams/AddLessonSequenceDiagram_5.puml
  docs/images/AddLessonSequenceDiagram_1.png
  docs/images/AddLessonSequenceDiagram_4.png
  docs/images/AddLessonSequenceDiagram_5.png
Labels: documentation

#177 Make lesson address and subject fields optional
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/model/lesson/LessonAddress.java
  src/main/java/seedu/address/model/lesson/Subject.java
Labels: enhancement

#178 Fix `assign` command bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: bug

#179 Fix bugs in `findlesson` and `findstudent` commands
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/parser/FindLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/FindStudentCommandParser.java
  src/main/java/seedu/address/model/lesson/LessonNameOrSubjectContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/NameOrTagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FindStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudentBookParserTest.java
Labels: bug

#180 Fix bug when editing student
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/EnrolledStudents.java
  src/main/java/seedu/address/model/student/EnrolledLessons.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
Labels: bug

#181 Update user guide
  docs/UserGuide.md
Labels: documentation

#182 Update command summary
  docs/UserGuide.md
Labels: documentation

#184 InfoPanel Bugfix
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonInfoCommand.java
  src/main/java/seedu/address/logic/commands/ViewStudentInfoCommand.java
  src/main/java/seedu/address/logic/commands/misc/InfoPanelTypes.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: bug
